### ISSUE TITLE
Passing Parameters between ViewModels 

### ISSUE THREAD

**Issue by talk2stephan** [xamarinhq/xamu-infrastructure#12]
I am using this method ` await serviceLocator.Get<INavigationService>()
                                        .NavigateAsync(AppPages.UserDetailPage);` Suppose if I wan't to pass some query parameters to MainViewModel to UserDetailViewModel, what additional information / code is required. I would like to pass logged in user details from MainViewModel to UserDetailViewModel

Also If I pass one parameter from MainViewModel how I receive the same in UserDetailViewModel

**Comment by markjulmar** [comment]
For cases like this where the data is not constant, you don't want to bind a single VM to the view - instead, you could create the `UserDetailViewModel` and populate it with the necessary data and then hand it to the `NavigateAsync` method:

```csharp
var navService = ...;
var userDetails = new UserDetailsViewModel { /* setup values from current VM */ }
navService.NavigateAsync(AppPages.UserDetailPage, userDetails);
```

This will set that object (`userDetails`) as the `BindingContext` for the page as part of it's creation - thereby handing it the data.

An alternative model would be to store the details in some other service (e.g. a `User.CurrentUser` sort of singleton, and then retrieve it in your `UserDetailsViewModel`. But I prefer the former approach where I control it as part of the navigation.

**Comment by talk2stephan** [comment]
`navService.NavigateAsync(AppPages.UserDetailPage, userDetails);` Does that means, the second argument will (**userDetails**) be the data context for **UserDetailPage**? Or you are asking to create the view model object from MainViewModel and pass that to UerDetailPage and set the data context?

Or If you simply passing only the object how I will get the **userDetails** object from **UserDetailViewModel** 

Yea. I don't think the second approach is good.

Suppose If i want to pass some dictionary values or Strings, what would be the best approach ?

**Comment by markjulmar** [comment]
Yes, that's exactly right -- whatever you pass (`object` type) will be set as the binding context for the page.

That nav wrapper doesn't really support arbitrary objects - but you could extend it by providing your own implementation of `INavigationService` and registering it .. then you could have your ViewModel's implement an interface for initialization, and have your custom nav service take the second parameter and instead use  the interface to initialize the VM with the data. Does that make sense?

**Comment by crazynitha** [comment]
@markjulmar - I think what @talk2stephan  requesting is a must to have feature. I don't think creating destination view_model object from source view_model  and setting the DataContext is a good approach. If you can enable the feature to pass some query string / object, that will become a real value add to the framework. 

I am also using xamu-infrastructure framework in our app. But haven't think about this feature. But yes If some one can enable this feature that would be really great.

**Comment by markjulmar** [comment]
Here would be what I propose:

1. Create a new interface `IInitViewModel` (or something like that)

```csharp
public interface IInitViewModel
{
   Task InitializeAsync(object parameter);
}
```

2. Add a second version of the `NavigateAsync` method which takes _three_ parameters
     a) View key
     b) ViewModel (can be null if view assigns directly)
     c) Parameter object (can be null)

3. Once the View has been created, check the `BindingContext` and see if it implements the above interface, if so, call the **init** method and pass it the parameter (which might be null).

This would allow for arbitrary initialization of the view model - including support for async.

What do you guys think? Should we also modify the existing behavior and _not_ assign a `BindingContext` if the view adds one as part of construction - instead look for the interface and go through the init pass?

**Comment by rkshnair** [comment]
Hi Mark,
Could please tell me, how I can pass parameters between viewmodel based on the new implementation? I cannot find any wiki information related to that.. Could you please help?

**Comment by markjulmar** [comment]
Hi @rkshnair .. see if this page helps: 

https://github.com/xamarinhq/xamu-infrastructure/wiki/Assigning-View-Models-and-passing-parameters
