### ISSUE TITLE
Ambiguous match found Error.

### ISSUE THREAD

**Issue by talk2stephan** [xamarinhq/xamu-infrastructure#13]
**I am getting ambiguous math found error while executing this statement** 
 public DependencyServiceWrapper()
 {
             genericGetMethod = GetType().GetTypeInfo().GetDeclaredMethod("Get"); 
}

Getting the error after taking your latest update. 

Please find the below stack trace

> System.TypeInitializationException: The type initializer for 'StoreFinder.App' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
05-06 13:47:50.503 E/mono    (12599):   at System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00059] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
05-06 13:47:50.503 E/mono    (12599):   at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) [0x0000e] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
05-06 13:47:50.503 E/mono    (12599):   at System.Reflection.TypeInfo.GetDeclaredMethod (System.String name) [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0

**Comment by markjulmar** [comment]
Yup, definitely a bug due to the second version of `Get` added. I'll push a fix shortly.
