### ISSUE TITLE
Page Navigation is not working in Android 

### ISSUE THREAD

**Issue by rkshnair** [xamarinhq/xamu-infrastructure#14]
Steps to reproduce the issue.
1. Launch the app
2. Navigate from MainPage to SubPage (A=>B , B=>C)
3. Its is working.

Close the app by clicking back button (Sub Pages to Main Page)
1. C=> B & B => A then close.
2. Try to re-launch the app by clicking the app icon.
3. the app freezes on startup (Navigation not working)

**Comment by markjulmar** [comment]
Hi @rkshnair --

I can't reproduce this - can you supply a sample project so we can look into it? Since we are using the built in `Navigation` support of Xamarin.Forms, it might be something in the framework itself.

**Comment by rkshnair** [comment]
After taking the latest nuget pack it is working. I think i was using an old version of the package. You can close the thread.
Sorry for the inconvenience

**Comment by rkshnair** [comment]
@markjulmar Hi Mark,

Suppose If I want to call some web service during the the page load. What could be the corresponding override method / method that can be leveraged in ViewModel. Or what is the best practice in our framework. Right now I can only see the constructor which will not allow me to call asnyc/ await method.

And in my project I am calling the method like this, Which itself creating issues. 

> protected override void OnBindingContextChanged()
        {
            base.OnBindingContextChanged();
            if (BindingContext is ExtendedSplashViewModel vm)
            {
                vm.InitializeAsync();
            }
        }
Could you please help.

**Comment by markjulmar** [comment]
Hi @rkshnair  --

Check out the [IViewModelNavigationInit](https://github.com/xamarinhq/xamu-infrastructure/wiki/IViewModelNavigationInit) interface. It has a method which gets called when the VM is associated to the view.

Alternatively, override the [Appearing](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.appearing?view=xamarin-forms) event on the `Page`, then call a method on your ViewModel to do your init. There's nothing wrong with calling methods from View > ViewModel - the View _has_ to know about the VM always. So just use it.

**Comment by crazynitha** [comment]
Hi @markjulmar 
How I can write Unit test to my ViewModel methods? Or else how to access my view model methods in my test class? Do you have any documentation or samples available?

Also to access the method I need to declare my method with "Public" scope right? Is it really good to write the code in that way? Could you please suggest.

I tried to create a mock DependancyService by inheriting **: IDependencyService**

`public class MockDependencyService : IDependencyService
    {
        readonly Dictionary<Type, object> registeredServices = new Dictionary<Type, object>();

        public void Register<T>(object impl)
        {
            this.registeredServices[typeof(T)] = impl;
        }

        public T Get<T>() where T : class
        {
            return (T)registeredServices[typeof(T)];
        }

        public void Register<T>() where T : class, new()
        {
            throw new NotImplementedException();
        }

        void IDependencyService.Register<T, TImpl>()
        {
            throw new NotImplementedException();
        }

        public void Register<T>(T impl) where T : class
        {
            throw new NotImplementedException();
        }

        public T Get<T>(DependencyScope scope) where T : class
        {
            throw new NotImplementedException();
        }
    }
}`

var vm = new MainViewModel(new MockDependencyService ());

But getting the below error

System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'

Also I tried to create a setup-class; Which is not even firing for me

[OneTimeSetUp]
        public void Setup()
        {
            var ds = new DependencyServiceStub();
            dependencyService = ds;
        }
