### ISSUE TITLE
Allow re-initialization of the library

### ISSUE THREAD

**Issue by DennisWelu** [xamarinhq/xamu-infrastructure#15]
Calling ```XamUInfrastructure.Init``` a 2nd time throws an exception, currently by design. However  with Xamarin Forms on Android in particular that can be problematic. In XF Android, if you use the Back button to back out of the app, the MainActivity is destroyed but the Application instance still hangs around. So if you re-launch the app, or re-activate it from the active list, it re-creates the MainActivity and XF App instance all again. I think the most common way of initializing 3rd party plugins is in the same ```MainActivity.OnCreate``` method where Xamarin Forms gets initialized, so for example:

```
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            
            XamUInfrastructure.Init(); // <-- Exception 2nd time

            LoadApplication(new App());
        }
```

Maybe calling Init again should be allowed? Which would allow new instances of alternative dependency services to be passed to the Init, which might rely on things like the new XF App instance or one of its members, to be established as the new instance for the library to use....

Here is an example project that illustrates the exception. Created from template, the only change was to add the Infrastructure nuget library and the 1 line above to the ```MainActivity.OnCreate```. Just run the app, hit the Android back button, then re-activate the app.

[InitAndroidAgain.zip](https://github.com/xamarinhq/xamu-infrastructure/files/2250085/InitAndroidAgain.zip)

**Comment by markjulmar** [comment]
Hi @DennisWelu  - V2.1 of the library in NuGet supports this as long as you don't try to change the dependency service (e.g. pass in `null` or use the empty Init like you are showing).

**Comment by DennisWelu** [comment]
Awesome. Thanks @markjulmar ! That was quick.

**Comment by rkshnair** [comment]
After this change where we need to call ' XamUInfrastructure.Init(); " In MainActivity ?
I am calling initializing this in my App.xaml.cs. What could be the impact if i update the nuget and whact changes I need to apply in my existing code?

**Comment by markjulmar** [comment]
Shouldn't impact you at all - the change was simply to skip the Init code if you had already called it once before. Since you are calling it in an `App` override, you are only calling it once anyway.

**Comment by crazynitha** [comment]
Hi Mark,
Could you please add a sample project, that demonstrates the use of our library.

**Comment by markjulmar** [comment]
Many of the Xamarin University labs use it. Check out: https://github.com/XamarinUniversity/XAM320/tree/master/Exercise%203/Final

Which uses it for MVVM.

**Comment by stezma** [comment]
Hi @markjulmar 

In the sample you have provided, for each viewmodel constructor we are creating the new instance of **DependencyServiceWrapper**, Is that implementation is correct? Is there any alternative way I can implement this?

 ```
  public MainViewModel() : this(new XamarinUniversity.Services.DependencyServiceWrapper())
   {
   }

   public MainViewModel(IDependencyService serviceLocator)
   {
       this.serviceLocator = serviceLocator;

       Quotes = new ObservableCollection<QuoteViewModel>(QuoteManager.Load(serviceLocator.Get<IQuoteLoader>())
                       .Select(q => new QuoteViewModel(q)));

       SelectedQuote = Quotes.FirstOrDefault();

       AddQuote = new AsyncDelegateCommand(OnAddQuote);
       DeleteQuote = new AsyncDelegateCommand<QuoteViewModel>(OnDeleteQuote);
       EditQuote = new AsyncDelegateCommand<QuoteViewModel>(OnEditQuote);
       ShowQuoteDetail = new AsyncDelegateCommand<QuoteViewModel>(OnShowQuoteDetails);
   }
```

**Comment by markjulmar** [comment]
That's ctor is just for unit tests. A real system would use the dependency service to create the MainViewModel so it would get injected in.

**Comment by stezma** [comment]
Could you please tell, How I can do that? 
In that case how I will call my `serviceLocator.Get<IQuoteLoader>()` method?

**Comment by markjulmar** [comment]
Do you need the default constructor? If you remove it, the markup extension _should_ call the parameterized one.

**Comment by stezma** [comment]
If I remove the ctor I am getting the below error

'HomeViewModel' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'IDependencyService.Register<T>()'

**Comment by stezma** [comment]
@markjulmar Do I need to provide sample app to reproduce the issue?

**Comment by markjulmar** [comment]
Sure - that would be great. I've been swamped the past few weeks, we are releasing a new product @ Ignite on Monday and it's consumed my life. If you could give me a simple example, I could perhaps go through it on the plane this weekend!

**Comment by stezma** [comment]
Pleas find the [code](https://drive.google.com/open?id=1aZdsJb2nxllxa0vBE2VDwxWEcn9gU6r6) here.
I have created two projects.
1. With constructor 
2. Without constructor. 

Could you please take a look into the code and please guide me to solve the issue.

Stez.

**Comment by stezma** [comment]
@markjulmar Did you get a chance to look in to the issue?

**Comment by markjulmar** [comment]
@stezma You don't need to register the View Models. You only need to register objects which are going to use an abstraction - e.g. where you are going to activate it as an interface. If you do this:

```csharp
var vm = dependencyService.Get<FirstViewModel>()
```

It will return a new VM - passing in parameters to the constructor. So just comment out your register functions and it works fine.

**Comment by stezma** [comment]
I commented the below code from my app.xaml.cs
```
   dependencyService.Register<FirstViewModel>();
   dependencyService.Register<SecondViewModel>();
   dependencyService.Register<CountryManager>();
```
Also when I call `var vm = dependencyService.Get<FirstViewModel>()
` The constructor is calling correctly. 

But from where I set the **BindingContext** for my view.  

As I said I am using the below line of code for setting the Binding Context.

```
 BindingContext="{infrastructure:DependencyService Type={x:Type viewModels:FirstViewModel},
                                                      FetchTarget=NewInstance}">
```
I was trying to generate the ViewModel along with my View and I don't want my ViewModel to be static. That is the reason I set the FetchTarget as NewInstance.

In the new approach how can I re-write this code? 

When I comment this `dependencyService.Register<FirstViewModel>();` the viewmodel is not creating.

**Comment by markjulmar** [comment]
Ah I see. That `DependencyServiceExtension` doesn't go through the library - it only uses the Forms version. So you have to register the VMs - in which case you can't use non-default constructors.

I'll change the extension to use our wrapper instead which will fix that - however, an easy way to fix it yourself is to move the `BindingContext` assignment to the constructor of the C# class. E.g.:

```csharp
public class FirstView : ContentPage
{
    public FirstView()
    {
        BindingContext = XamUInfrastructure.ServiceLocator.Get<FirstViewModel>();
    }
}
```

Then it will work how you expect it to.

**Comment by stezma** [comment]
@markjulmar Okay. Thanks for clarifying this.
I will try with this method. Also as you said, if you can update the **DependencyServiceExtension** that would be great. In that case I can avoid writing the code in my code behind ;).

Once again thank you so much for helping me out. 👍

**Comment by markjulmar** [comment]
Good news - I changed the `DependencyServiceExtension` to work with the wrapper. It's a breaking change - use `Scope` instead of `FetchTarget`. So it looks like this:

```xml
 BindingContext="{infrastructure:DependencyService Type={x:Type viewModels:FirstViewModel},
                                                      Scope=NewInstance}">
```

You shouldn't need to register ViewModels with this version.

**Comment by markjulmar** [comment]
By the way, there's an alternative you could use as well. Rather than using that extension, pass the **ViewModel** into the Page constructor.

```csharp
public partial class MainPage : ContentPage
{
   public MainPage(MainViewModel viewModel)
   {
      BindingContext = viewModel;
      InitializeComponent();
   }
}
```

The way you get this to work is to register the pages like this:

```csharp
navService.RegisterPage(AppPages.Main, dependencyService.Get<MainPage>);
```

Notice that we use the dependency service to "get" the main page - it's not registered at all - but because we are asking for a concrete class, the wrapper will use reflection to create it and _pass_ in the view model automatically. In fact, you can have parameters be passed to the ViewModel too! For example, it could be this:

```csharp
public MainViewModel(IDependencyService serviceLocator)
{
}
```

In this case, the wrapper would look at what it needs to build (the `MainViewModel`) and pass in the dependency service - which _is_ a registered type. It will all just work. Pretty cool.

**Comment by stezma** [comment]
That's Great.. Thanks you so much for this quick fix and detailed explanation. 👍 💯
