### ISSUE TITLE
After Updating the Nuget Package the navigation is not working 

### ISSUE THREAD

**Issue by crazynitha** [xamarinhq/xamu-infrastructure#17]
After updating the nuget package the page navigation is not working. 
I have created a sample application that reproduce the issue.

https://drive.google.com/open?id=1crCrSttDzWQP_n44iUeKo-7clbQY4WIa

**Comment by crazynitha** [comment]
@markjulmar Are you able to reproduce the issue in your end? Is it anything missing from my side or is it a know issue? Could you please respond?

**Comment by markjulmar** [comment]
Let me look into it this weekend. Until then, just revert back to the prior release; the only thing that was added was the ability to call `Initialize` more than once so you aren't missing anything.

**Comment by markjulmar** [comment]
Hi @crazynitha  --

You actually have a bug in your code that's being exposed with this change. You are registering _two_ copies of a navigation service.

Generally speaking, you should _not_ use `DependencyService` directly. Instead, use the abstraction returned by `XamUInfrastructure.Init` - it extends the built-in dependency service and provides other ways to initialize objects.

So, I'd cache off the interface returned by the `Init` method and use it to retrieve the `INavigationService` instead of adding it yourself (that's how you ended up with two -- `Init` adds one too).

Alternatively, I got your code to work by changing the `Init` method to be:

```csharp
XamUInfrastructure.Init(null, RegisterBehavior.MessageVisualizer);
```

With this, we are *not* registering the `INavigationService` and therefore your version registered in the `App` constructor will get used globally. Otherwise, some things are using one and your code is using the other.

I hope that helps!
mark

**Comment by crazynitha** [comment]
Hi @markjulmar Thanks for clarifying this.
Based on your [advice ](https://github.com/xamarinhq/xamu-infrastructure/issues/15) I am using this [link](https://github.com/XamarinUniversity/XAM320/blob/master/Exercise%203/Final/GreatQuotes/GreatQuotes/App.xaml.cs) as my reference for learning. 

Based on your suggestion I have made some changes to my app.xaml.

```
    public partial class App : Application
    {
        static IDependencyService _dependencyService;
        public App()
        {
            InitializeComponent();
            _dependencyService.Register<INavigationService, FormsNavigationPageService>();
            var naviPage = new NavigationPage(new MainPage());
            MainPage = naviPage;

        }
        static App()
        {
            _dependencyService = XamUInfrastructure.Init();
            // Register dependencies.
            _dependencyService.Register<MainViewModel>();
            _dependencyService.Register<DetailViewModel>();
            RegisterPages();
            // Register standard XamU services

        }

        private static void RegisterPages()
        {
            var nService = _dependencyService.Get<INavigationService>();
            var navService = (FormsNavigationPageService)nService;

            navService?.RegisterPage(AppPages.Main, () => new MainPage());
            navService?.RegisterPage(AppPages.Detail, () => new DetailPage());
        }
   }
```

      I have moved the _dependencyService = XamUInfrastructure.Init(); to my static constructor along with RegisterPages(). Since  i put the app to background by clicking the center button, and if i select the app by clicking the app icon in the applist. It again going to apps constructor. 
	  
But right now, because of  the `_dependencyService.Register<INavigationService, FormsNavigationPageService>();` and initializing  new NavigationPage(new MainPage()); it opens the application again from main page.
	  
	  I am totally confused about configuring the framework against page life cycle events. So I would like to request you to provide a sample. So that fresher like me can understand the usage of framework in a better way.

The sample project [https://github.com/XamarinUniversity/XAM320/](link) you already provided is not updated.

Please help.

**Comment by markjulmar** [comment]
There is no need for the static constructor. Move it all to your `App()` constructor -- that is only called once per app launch. In addition, there's no need for the cast, there's a [IPageNavigationService](https://github.com/xamarinhq/xamu-infrastructure/blob/master/src/XamU.Infrastructure/Interfaces/INavigationPageService.cs) which provides the register methods.

So you can just do this:

```
public partial class App : Application
{
    public App()
    {
        var dependencyService = XamUInfrastructure.Init();
        
        // Register View Models
        dependencyService.Register<MainViewModel>();
        dependencyService.Register<DetailViewModel>();
        
        // Register pages with nav service
        RegisterPages(dependencyService.Get<IPageNavigationService>());

        InitializeComponent();

        MainPage = new NavigationPage(new MainPage());
    }

    void RegisterPages(IPageNavigationService navService)
    {
        navService.RegisterPage(AppPages.Main, () => new MainPage());
        navService.RegisterPage(AppPages.Detail, () => new DetailPage());
    }
}
```

**Comment by markjulmar** [comment]
Ah, ok -- sorry, I forgot Android's sillyness. Move all that code back into your static ctor so it's only executed once, like this:

> Alternatively, you could put a static flag and do 1-time init logic if you prefer not to have a static constructor.

```
public partial class App : Application
{
    public App()
    {
        InitializeComponent();
        MainPage = new NavigationPage(new MainPage());
    }

   static App()
   {
        var dependencyService = XamUInfrastructure.Init();
        
        // Register View Models
        dependencyService.Register<MainViewModel>();
        dependencyService.Register<DetailViewModel>();
        
        // Register pages with nav service
        RegisterPages(dependencyService.Get<IPageNavigationService>());
   }

    void RegisterPages(IPageNavigationService navService)
    {
        navService.RegisterPage(AppPages.Main, () => new MainPage());
        navService.RegisterPage(AppPages.Detail, () => new DetailPage());
    }
}
```

**Comment by crazynitha** [comment]
Thanks @markjulmar Thanks for clarifying my doubt 👍
