### ISSUE TITLE
[Feature Request] Core package without Xamarin.Forms Dependency

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarinhq/xamu-infrastructure#2]
Would be nice to have a core package similar to MvvmHelpers that doesn't have a dependency on it to Xamarin.Forms.

**Comment by markjulmar** [comment]
[Completed](https://github.com/xamarinhq/xamu-infrastructure/commit/47e79ccc49d66c68b26a1f92be24404e661c2fac)
