### ISSUE TITLE
Missing constraint in IDependencyService?

### ISSUE THREAD

**Issue by DennisWelu** [xamarinhq/xamu-infrastructure#3]
3 of the 4 methods defined on IDependencyService have the 'class' constraint: https://github.com/xamarinhq/xamu-infrastructure/blob/2082dd1d7b024ef8b697429820a5ee608de96cd5/src/XamU.Core/Interfaces/IDependencyService.cs

But this one does not: https://github.com/xamarinhq/xamu-infrastructure/blob/2082dd1d7b024ef8b697429820a5ee608de96cd5/src/XamU.Core/Interfaces/IDependencyService.cs#L52

Which causes me a specific problem trying to wrap/use TinyIoC as the dependency service.

Is this constraint intentionally left off? Or is it an oversight so it could be added...

**Comment by markjulmar** [comment]
It's more of an oversight -- it can be added without any impact. I'll see if I can get to that today!

**Comment by markjulmar** [comment]
Although - it shouldn't impact TinyIoC, what error are you getting when you try to wrap that service?

**Comment by DennisWelu** [comment]
Awesome. Thanks Mark! Otherwise if you need help I could fork and submit a PR. Here's the error:

error CS0452: The type 'T' must be a reference type in order to use it as parameter 'RegisterType' in the generic type or method 'TinyIoCContainer.Register<RegisterType>(RegisterType)'

The code in question in the wrapper looks like this, where "Instance" is the TinyIoCContainer instance:

```
        void IDependencyService.Register<T>(T impl)
        {
            Instance.Register(impl);
        }
```

**Comment by markjulmar** [comment]
Fixed with [1.0.161128](https://github.com/xamarinhq/xamu-infrastructure/commit/caac152d86029f68490d8ebf06479bf78573a469) (pushed to NuGet)

**Comment by DennisWelu** [comment]
So...strange. @markjulmar wondering if you have any idea why this would be. The update worked perfectly fine in my iOS and Droid XF projects, but the UWP project did not. When I go to the definition of IDependencyService it lists 2 versions as available (but they look the same in the popup list). I've reviewed the changeset and don't see anything UWP specific. Would there be something in the NuGet package build that didn't get updated for UWP?

**Comment by markjulmar** [comment]
There's no platform-specific code; my guess is the UWP project has the older NuGet. VS does that sometimes. Close VS, delete the packages/bin/obj folders and reopen your project and make sure there are no packages needing to be "consolidated" according to NuGet.

**Comment by DennisWelu** [comment]
Yeah that crossed my mind but didn't seem to help. I tried on a 2nd machine too and same problem. Have tried uninstalling/reinstalling the package. Have verified the version number of the package compare to the iOS and Droid packages. The main difference as far as NuGet goes is the UWP project uses the newer project.json for managing packages and not packages.config.

**Comment by DennisWelu** [comment]
I've been working around this on UWP hoping it clears itself up sometime. I even did a "nuget locals all -clear" with nuget.exe but nothing changed. Will keep poking at it now and then. Very strange.

**Comment by markjulmar** [comment]
Have you tried building from source and adding the two DLLs directly? I'm not seeing that issue on a UWP app I have.. but I am seeing some other weird issue on VS2017 ; I'm investigating now.

**Comment by DennisWelu** [comment]
The thought crossed my mind...then after reading your comment I was like shoot, I can just reference the assemblies in the packages folder created for the iOS and Android projects to test that (still using the packages.config nuget approach there). 

**And that worked!** 

So yeah...something weird about the nuget package in this UWP app. Probably something project specific or environment specific (recreated this on a 2nd machine locally but it once had the project built on it previously so...not a clean test).

Thanks for the ideas. If I ever figure out a better cause will let you know...

**Comment by markjulmar** [comment]
I found the issue .. the Infrastructure NuGet package was referencing the older Core package; so if you updated Core _first_, then it all worked, but if you updated Infrastructure, then it would _not_ update Core. It's fixed in the latest NuGet upload - no code changes; sorry about that!

**Comment by DennisWelu** [comment]
Hah. Funny. If I had a nickel for every time... No worries, appreciating the help. Nice library, btw, it's "right sized" for me...covers the common fundamental needs without heavy inter-dependencies between components. Thank you!

**Comment by DennisWelu** [comment]
Confirmed NuGet update worked...thanks again. :-)
