### ISSUE TITLE
Error referencing NavigateTo command from XAML

### ISSUE THREAD

**Issue by DennisWelu** [xamarinhq/xamu-infrastructure#4]
Existing XAML page, following directions here: https://github.com/xamarinhq/xamu-infrastructure/wiki/NavigationToCommand. Getting a build error (tried both Android and UWP).

Also the wiki doc is not quite right, it says to reference cmds:NavigationCommands.NavigateToCommand but the actual static reference is cmds:NavigationCommands.NavigateTo

** To reproduce **
1.  Add namespace xmlns:cmds="clr-namespace:XamarinUniversity.Commands;assembly=XamU.Infrastructure"
2. Specify a command value as Command="{x:Static cmds:NavigationCommands.NavigateTo}"
3. Build

**Expected behavior:**
Clean build

**Actual behavior:**
...\.nuget\packages\Xamarin.Forms\2.3.3.175\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.targets(62,3): error : Member 'XamarinUniversity.Commands.NavigateToCommand' is declared in another module and needs to be imported

**Comment by markjulmar** [comment]
I've fixed the documentation to properly reflect the namespace and the name of the command.
