### ISSUE TITLE
Reset Navigation Stack

### ISSUE THREAD

**Issue by correianet** [xamarinhq/xamu-infrastructure#5]
I need some reset navigation stack because the INavigation property in FormsNavigationService is cached on first call and when I change root page creating a new NavigationPage that NavigationService lost the stack and doesn't work anymore.

**Comment by markjulmar** [comment]
Are you thinking just to clear the stack, or to replace it with another set of possible pages? I could see both use cases.

**Comment by correianet** [comment]
Hi Mark! Thanks for your answer. 
So, I need to clear the stack with a new NavigationPage because with that I can reset the stack with a new root page instantly. Navigation methods fails if I change the MainPage with a new NavigationPage because in wrapper INavigationService, the INavigation property is cached in first time that is used.

I'd like not to have a dependency with Page type in my ViewModel, so I think we can remove cache from INavigation property or offer PopToRoot in wrapper and remove the requirement to create a new NavigationPage or access INavigation from wrapper.

**Comment by markjulmar** [comment]
Added support for this in [this commit](https://github.com/xamarinhq/xamu-infrastructure/commit/6482df8e72dcfca4ad35b92b8f5fa29e1322e139).
