### ISSUE TITLE
Problem with binding Stepper to ObservableDictionary<TKey,TValue>

### ISSUE THREAD

**Issue by Afshin1980** [xamarinhq/xamu-infrastructure#9]
Hello 
i have a problem to bind Stepper to Dictionary in code behind . when i try to bind it i receive this error

Object reference not set to an instance of an object

i can bind TextProperty of Entry to the Dictionary but for Stepper I can't

This Code work for Entry:

Entry = new Entry { HeightRequest = 40,HorizontalOptions = LayoutOptions.FillAndExpand};
StackLayoutMap.Children.Add(Entry);
Entry.SetBinding(Entry.TextProperty, "Dictionary[" + item.FieldID.ToString() + "]");

But this Code doesn't work for Stepper

Stepper = new Stepper();
StackLayoutMap.Children.Add(Stepper);
Stepper.SetBinding(Stepper.ValueProperty,"Dictionary[" + item.FieldID.ToString() + "]");

**Comment by markjulmar** [comment]
Use `Stepper.SetBinding(Stepper.ValueProperty, new Binding($"[{item.FieldId}]"));`

The binding path should be `"[index]"` .. don't use **Dictionary** in the path.

**Comment by Afshin1980** [comment]
thank you so much
